# Generated by Django 3.0.5 on 2020-04-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('type1', models.CharField(max_length=64)),
                ('type2', models.CharField(blank=True, max_length=64)),
                ('base_stat_speed', models.IntegerField()),
                ('base_stat_spdef', models.IntegerField()),
                ('base_stat_spatk', models.IntegerField()),
                ('base_stat_atk', models.IntegerField()),
                ('base_stat_def', models.IntegerField()),
                ('sprites_back_default', models.URLField(blank=True)),
                ('sprites_back_female', models.URLField(blank=True)),
                ('sprites_back_shiny', models.URLField(blank=True)),
                ('sprites_back_shiny_female', models.URLField(blank=True)),
                ('sprites_front_default', models.URLField(blank=True)),
                ('sprites_front_female', models.URLField(blank=True)),
                ('sprites_front_shiny', models.URLField(blank=True)),
                ('sprites_front_shiny_female', models.URLField(blank=True)),
            ],
        ),
    ]
